name: 'Kubernetes set context'
description: 'Login kubernetes'
inputs: 
  creds:
    description: 'Azure credentials i.e. output of az ad sp create-for-rback'
  subscriptionId:
    description: 'Subscription ID'
    required: false
    default: ''
  resourceGroupName:
    description: 'Resource Group Name'
    required: false
    default: ''
  clusterName:
    description: 'AKS Cluster Name'
    required: false
    default: ''
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node'
  main: 'lib/login.js'