name: 'Kubernetes set context'
description: 'Kubernetes set context'
inputs: 
  kubeconfig:
    description: 'Kubernetes Config'
    required: false
    default: ''
  context:
    description: 'If your kubeconfig has multiple contexts, use this field to use a specific context, otherwise the default one would be chosen'
    required: false
    default: ''

  k8s-url:
    description: 'Cluster Url'
    required: false
    default: ''
  k8s-secret:
    description: 'Service account token'
    required: false
    default: ''
  
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node12'
  main: 'lib/login.js'
