name: 'Docker Login'
description: 'Login docker'
inputs: 
  username:
    description: 'Docker username'
    required: true
    default: ''
  password:
    description: 'Docker password'
    required: true
    default: ''
  loginServer:
    description: 'Login Server'
    required: true
    default: 'index.docker.io'
branding:
  color: 'green'
runs:
  using: 'node'
  main: 'lib/login.js'